spring:
  datasource:
    url: jdbc:postgresql://dpg-cicrhsiip7vnjjm6qkq0-a.frankfurt-postgres.render.com/hits_application_service_db
    username: admin
    password: V8XwZzWKlPVMGKZi4ubyV4n1LfrDAIDh

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    serialization:
      fail-on-empty-beans: false
